services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stagemarkt
      POSTGRES_PASSWORD: stagemarkt
      POSTGRES_DB: stagemarkt
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stagemarkt"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  scraper:
    build: ./scraper
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://stagemarkt:stagemarkt@postgres:5432/stagemarkt
      PROXY: http://user-vasie_dDUVn:UG_d8SkA8NYGll@ddc.oxylabs.io:8001
    command: sh -c "python main.py && tail -f /dev/null"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.scraper.schedule: "0 0 * * * *"
      ofelia.job-exec.scraper.command: "python main.py"

  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - scraper
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  pgdata:
