services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stagemarkt
      POSTGRES_PASSWORD: stagemarkt
      POSTGRES_DB: stagemarkt
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stagemarkt"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

volumes:
  pgdata: